2017-11-18 11:37:09,009 ERROR 12595 nodejs.ClusterClientNoResponseError: client no response in 6131742ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 12595
hostname: admindeAir.lan

2017-11-18 13:07:18,357 ERROR 12595 nodejs.ClusterClientNoResponseError: client no response in 908755ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 12595
hostname: admindeAir.lan

2017-11-18 13:54:44,233 ERROR 12595 nodejs.ClusterClientNoResponseError: client no response in 1765713ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 12595
hostname: admindeAir.lan

2017-11-18 14:35:35,192 ERROR 12595 nodejs.ClusterClientNoResponseError: client no response in 2450953ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 12595
hostname: admindeAir.lan

2017-11-18 15:20:44,349 ERROR 12595 nodejs.ClusterClientNoResponseError: client no response in 2708686ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 12595
hostname: admindeAir.lan

2017-11-18 16:35:45,195 ERROR 17194 [-/127.0.0.1/-/3ms GET /api/topics/] nodejs.ReferenceError: cosnole is not defined
    at new TopicsController (/Users/baixing/kingKong/app/controller/topics.js:5:9)
    at Object.classControllerMiddleware (/Users/baixing/kingKong/node_modules/egg-core/lib/loader/mixin/controller.js:81:26)
    at classControllerMiddleware.next (<anonymous>)
    at Object.dispatch (/Users/baixing/kingKong/node_modules/koa-router/lib/router.js:334:5)
    at dispatch.next (<anonymous>)
    at onFulfilled (/Users/baixing/kingKong/node_modules/co/index.js:65:19)
    at /Users/baixing/kingKong/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (/Users/baixing/kingKong/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/baixing/kingKong/node_modules/co/index.js:118:63)

pid: 17194
hostname: admindeAir.lan

2017-11-18 16:48:03,546 ERROR 17645 [-/127.0.0.1/-/76ms GET /userLog/usage/] nodejs.TypeError: logs is not iterable
    at UserLogController.usage (/Users/baixing/kingKong/app/controller/userLog.js:11:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 17645
hostname: admindeAir.lan

2017-11-18 19:37:11,748 ERROR 15445 nodejs.ClusterClientNoResponseError: client no response in 9001777ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 15445
hostname: admindeAir.lan

2017-11-18 20:28:59,178 ERROR 15445 nodejs.ClusterClientNoResponseError: client no response in 2407217ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 15445
hostname: admindeAir.lan

2017-11-18 20:54:04,845 ERROR 15445 nodejs.ClusterClientNoResponseError: client no response in 425505ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 15445
hostname: admindeAir.lan

2017-11-18 22:31:36,214 ERROR 15445 nodejs.ClusterClientNoResponseError: client no response in 2951015ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 15445
hostname: admindeAir.lan

2017-11-18 22:35:46,851 ERROR 15445 nodejs.ClusterClientNoResponseError: client no response in 168135ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 15445
hostname: admindeAir.lan

2017-11-19 00:06:00,121 ERROR 15445 nodejs.ClusterClientNoResponseError: client no response in 3610787ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 15445
hostname: admindeAir.lan

2017-11-19 08:58:35,309 ERROR 15445 nodejs.ClusterClientNoResponseError: client no response in 31915181ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 15445
hostname: admindeAir.lan

2017-11-19 19:35:39,546 ERROR 15445 nodejs.ClusterClientNoResponseError: client no response in 34122244ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 15445
hostname: admindeAir.lan

2017-11-19 21:56:42,860 ERROR 15445 nodejs.ClusterClientNoResponseError: client no response in 3266394ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 15445
hostname: admindeAir.lan

2017-11-19 23:51:03,669 ERROR 15445 nodejs.ClusterClientNoResponseError: client no response in 4220183ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 15445
hostname: admindeAir.lan

2017-11-20 09:32:35,983 ERROR 15445 nodejs.ClusterClientNoResponseError: client no response in 34892210ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 15445
hostname: admindeAir.lan

2017-11-20 18:27:00,605 ERROR 37267 [-/127.0.0.1/-/125ms GET /api/userLog/usage/] nodejs.TypeError: result.map is not a function
    at userLog.getTotalTime (/Users/baixing/kingKong/app/service/userLog.js:55:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 37267
hostname: admindeMacBook-Air.local

2017-11-20 18:27:01,823 ERROR 37267 [-/127.0.0.1/-/41ms GET /api/userLog/usage/] nodejs.TypeError: result.map is not a function
    at userLog.getTotalTime (/Users/baixing/kingKong/app/service/userLog.js:55:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 37267
hostname: admindeMacBook-Air.local

2017-11-20 18:28:37,188 ERROR 37267 [-/127.0.0.1/-/101ms GET /api/userLog/usage/] nodejs.TypeError: result.map is not a function
    at userLog.getTotalTime (/Users/baixing/kingKong/app/service/userLog.js:55:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 37267
hostname: admindeMacBook-Air.local

2017-11-21 10:40:49,139 ERROR 34395 nodejs.ClusterClientNoResponseError: client no response in 818277ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/baixing/kingKong/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
name: 'ClusterClientNoResponseError'
pid: 34395
hostname: admindeMacBook-Air.local

2017-11-21 11:35:27,026 ERROR 46219 [-/127.0.0.1/-/99ms GET /api/userLog/usage/] nodejs.TypeError: Cannot read property 'logintype' of undefined
    at userLog.getTotalTime (/Users/baixing/kingKong/app/service/userLog.js:23:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 46219
hostname: admindeMacBook-Air.local

